// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.example.tutorial;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Person)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    java.util.List<com.example.tutorial.AddressBookProtos.Person.PhoneNumber> 
        getPhonesList();
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    com.example.tutorial.AddressBookProtos.Person.PhoneNumber getPhones(int index);
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    int getPhonesCount();

    /**
     * <code>.google.protobuf.Timestamp last_updated = 9;</code>
     */
    boolean hasLastUpdated();
    /**
     * <code>.google.protobuf.Timestamp last_updated = 9;</code>
     */
    com.google.protobuf.Timestamp getLastUpdated();
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code tutorial.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageLite<
          Person, Person.Builder> implements
      // @@protoc_insertion_point(message_implements:tutorial.Person)
      PersonOrBuilder {
    private Person() {
      name_ = "";
      email_ = "";
      phones_ = emptyProtobufList();
    }
    /**
     * Protobuf enum {@code tutorial.Person.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      @java.lang.Override
      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              @java.lang.Override
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return PhoneTypeVerifier.INSTANCE;
      }

      private static final class PhoneTypeVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PhoneTypeVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return PhoneType.forNumber(number) != null;
              }
            };

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.Person.PhoneType)
    }

    public interface PhoneNumberOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tutorial.Person.PhoneNumber)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>string number = 1;</code>
       */
      java.lang.String getNumber();
      /**
       * <code>string number = 1;</code>
       */
      com.google.protobuf.ByteString
          getNumberBytes();

      /**
       * <code>.tutorial.Person.PhoneType type = 2;</code>
       */
      int getTypeValue();
      /**
       * <code>.tutorial.Person.PhoneType type = 2;</code>
       */
      com.example.tutorial.AddressBookProtos.Person.PhoneType getType();
    }
    /**
     * Protobuf type {@code tutorial.Person.PhoneNumber}
     */
    public  static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessageLite<
            PhoneNumber, PhoneNumber.Builder> implements
        // @@protoc_insertion_point(message_implements:tutorial.Person.PhoneNumber)
        PhoneNumberOrBuilder {
      private PhoneNumber() {
        number_ = "";
      }
      public static final int NUMBER_FIELD_NUMBER = 1;
      private java.lang.String number_;
      /**
       * <code>string number = 1;</code>
       */
      @java.lang.Override
      public java.lang.String getNumber() {
        return number_;
      }
      /**
       * <code>string number = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNumberBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(number_);
      }
      /**
       * <code>string number = 1;</code>
       */
      private void setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        number_ = value;
      }
      /**
       * <code>string number = 1;</code>
       */
      private void clearNumber() {
        
        number_ = getDefaultInstance().getNumber();
      }
      /**
       * <code>string number = 1;</code>
       */
      private void setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        number_ = value.toStringUtf8();
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private int type_;
      /**
       * <code>.tutorial.Person.PhoneType type = 2;</code>
       */
      @java.lang.Override
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.tutorial.Person.PhoneType type = 2;</code>
       */
      @java.lang.Override
      public com.example.tutorial.AddressBookProtos.Person.PhoneType getType() {
        com.example.tutorial.AddressBookProtos.Person.PhoneType result = com.example.tutorial.AddressBookProtos.Person.PhoneType.forNumber(type_);
        return result == null ? com.example.tutorial.AddressBookProtos.Person.PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <code>.tutorial.Person.PhoneType type = 2;</code>
       */
      private void setTypeValue(int value) {
          type_ = value;
      }
      /**
       * <code>.tutorial.Person.PhoneType type = 2;</code>
       */
      private void setType(com.example.tutorial.AddressBookProtos.Person.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
      }
      /**
       * <code>.tutorial.Person.PhoneType type = 2;</code>
       */
      private void clearType() {
        
        type_ = 0;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!number_.isEmpty()) {
          output.writeString(1, getNumber());
        }
        if (type_ != com.example.tutorial.AddressBookProtos.Person.PhoneType.MOBILE.getNumber()) {
          output.writeEnum(2, type_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (!number_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getNumber());
        }
        if (type_ != com.example.tutorial.AddressBookProtos.Person.PhoneType.MOBILE.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      public static com.example.tutorial.AddressBookProtos.Person.PhoneNumber parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.example.tutorial.AddressBookProtos.Person.PhoneNumber parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.example.tutorial.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.example.tutorial.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.example.tutorial.AddressBookProtos.Person.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.example.tutorial.AddressBookProtos.Person.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.example.tutorial.AddressBookProtos.Person.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static com.example.tutorial.AddressBookProtos.Person.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.example.tutorial.AddressBookProtos.Person.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static com.example.tutorial.AddressBookProtos.Person.PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.example.tutorial.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static com.example.tutorial.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
      public static Builder newBuilder(com.example.tutorial.AddressBookProtos.Person.PhoneNumber prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
      }

      /**
       * Protobuf type {@code tutorial.Person.PhoneNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.example.tutorial.AddressBookProtos.Person.PhoneNumber, Builder> implements
          // @@protoc_insertion_point(builder_implements:tutorial.Person.PhoneNumber)
          com.example.tutorial.AddressBookProtos.Person.PhoneNumberOrBuilder {
        // Construct using com.example.tutorial.AddressBookProtos.Person.PhoneNumber.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>string number = 1;</code>
         */
        @java.lang.Override
        public java.lang.String getNumber() {
          return instance.getNumber();
        }
        /**
         * <code>string number = 1;</code>
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
            getNumberBytes() {
          return instance.getNumberBytes();
        }
        /**
         * <code>string number = 1;</code>
         */
        public Builder setNumber(
            java.lang.String value) {
          copyOnWrite();
          instance.setNumber(value);
          return this;
        }
        /**
         * <code>string number = 1;</code>
         */
        public Builder clearNumber() {
          copyOnWrite();
          instance.clearNumber();
          return this;
        }
        /**
         * <code>string number = 1;</code>
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setNumberBytes(value);
          return this;
        }

        /**
         * <code>.tutorial.Person.PhoneType type = 2;</code>
         */
        @java.lang.Override
        public int getTypeValue() {
          return instance.getTypeValue();
        }
        /**
         * <code>.tutorial.Person.PhoneType type = 2;</code>
         */
        public Builder setTypeValue(int value) {
          copyOnWrite();
          instance.setTypeValue(value);
          return this;
        }
        /**
         * <code>.tutorial.Person.PhoneType type = 2;</code>
         */
        @java.lang.Override
        public com.example.tutorial.AddressBookProtos.Person.PhoneType getType() {
          return instance.getType();
        }
        /**
         * <code>.tutorial.Person.PhoneType type = 2;</code>
         */
        public Builder setType(com.example.tutorial.AddressBookProtos.Person.PhoneType value) {
          copyOnWrite();
          instance.setType(value);
          return this;
        }
        /**
         * <code>.tutorial.Person.PhoneType type = 2;</code>
         */
        public Builder clearType() {
          copyOnWrite();
          instance.clearType();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:tutorial.Person.PhoneNumber)
      }
      @java.lang.Override
      @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
      protected final java.lang.Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          java.lang.Object arg0, java.lang.Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new com.example.tutorial.AddressBookProtos.Person.PhoneNumber();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            com.example.tutorial.AddressBookProtos.Person.PhoneNumber other = (com.example.tutorial.AddressBookProtos.Person.PhoneNumber) arg1;
            number_ = visitor.visitString(!number_.isEmpty(), number_,
                !other.number_.isEmpty(), other.number_);
            type_ = visitor.visitInt(type_ != 0, type_,    other.type_ != 0, other.type_);
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            if (extensionRegistry == null) {
              throw new java.lang.NullPointerException();
            }
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  case 10: {
                    java.lang.String s = input.readStringRequireUtf8();

                    number_ = s;
                    break;
                  }
                  case 16: {
                    int rawValue = input.readEnum();

                    type_ = rawValue;
                    break;
                  }
                  default: {
                    if (!parseUnknownField(tag, input)) {
                      done = true;
                    }
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<com.example.tutorial.AddressBookProtos.Person.PhoneNumber> parser = PARSER;
            if (parser == null) {
              synchronized (com.example.tutorial.AddressBookProtos.Person.PhoneNumber.class) {
                parser = PARSER;
                if (parser == null) {
                  parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:tutorial.Person.PhoneNumber)
      private static final com.example.tutorial.AddressBookProtos.Person.PhoneNumber DEFAULT_INSTANCE;
      static {
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = new PhoneNumber();
      }

      public static com.example.tutorial.AddressBookProtos.Person.PhoneNumber getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<PhoneNumber> PARSER;

      public static com.google.protobuf.Parser<PhoneNumber> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.String name_;
    /**
     * <code>string name = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>string name = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 1;</code>
     */
    private void setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <code>string name = 1;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 1;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>int32 id = 2;</code>
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>int32 id = 2;</code>
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>int32 id = 2;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.String email_;
    /**
     * <code>string email = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      return email_;
    }
    /**
     * <code>string email = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>string email = 3;</code>
     */
    private void setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
    }
    /**
     * <code>string email = 3;</code>
     */
    private void clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>string email = 3;</code>
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value.toStringUtf8();
    }

    public static final int PHONES_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<com.example.tutorial.AddressBookProtos.Person.PhoneNumber> phones_;
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.tutorial.AddressBookProtos.Person.PhoneNumber> getPhonesList() {
      return phones_;
    }
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public java.util.List<? extends com.example.tutorial.AddressBookProtos.Person.PhoneNumberOrBuilder> 
        getPhonesOrBuilderList() {
      return phones_;
    }
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    @java.lang.Override
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    @java.lang.Override
    public com.example.tutorial.AddressBookProtos.Person.PhoneNumber getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public com.example.tutorial.AddressBookProtos.Person.PhoneNumberOrBuilder getPhonesOrBuilder(
        int index) {
      return phones_.get(index);
    }
    private void ensurePhonesIsMutable() {
      if (!phones_.isModifiable()) {
        phones_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(phones_);
       }
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    private void setPhones(
        int index, com.example.tutorial.AddressBookProtos.Person.PhoneNumber value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePhonesIsMutable();
      phones_.set(index, value);
    }
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    private void setPhones(
        int index, com.example.tutorial.AddressBookProtos.Person.PhoneNumber.Builder builderForValue) {
      ensurePhonesIsMutable();
      phones_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    private void addPhones(com.example.tutorial.AddressBookProtos.Person.PhoneNumber value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePhonesIsMutable();
      phones_.add(value);
    }
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    private void addPhones(
        int index, com.example.tutorial.AddressBookProtos.Person.PhoneNumber value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePhonesIsMutable();
      phones_.add(index, value);
    }
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    private void addPhones(
        com.example.tutorial.AddressBookProtos.Person.PhoneNumber.Builder builderForValue) {
      ensurePhonesIsMutable();
      phones_.add(builderForValue.build());
    }
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    private void addPhones(
        int index, com.example.tutorial.AddressBookProtos.Person.PhoneNumber.Builder builderForValue) {
      ensurePhonesIsMutable();
      phones_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    private void addAllPhones(
        java.lang.Iterable<? extends com.example.tutorial.AddressBookProtos.Person.PhoneNumber> values) {
      ensurePhonesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, phones_);
    }
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    private void clearPhones() {
      phones_ = emptyProtobufList();
    }
    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    private void removePhones(int index) {
      ensurePhonesIsMutable();
      phones_.remove(index);
    }

    public static final int LAST_UPDATED_FIELD_NUMBER = 9;
    private com.google.protobuf.Timestamp lastUpdated_;
    /**
     * <code>.google.protobuf.Timestamp last_updated = 9;</code>
     */
    @java.lang.Override
    public boolean hasLastUpdated() {
      return lastUpdated_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 9;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getLastUpdated() {
      return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 9;</code>
     */
    private void setLastUpdated(com.google.protobuf.Timestamp value) {
      if (value == null) {
        throw new NullPointerException();
      }
      lastUpdated_ = value;
      
      }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 9;</code>
     */
    private void setLastUpdated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      lastUpdated_ = builderForValue.build();
      
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 9;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeLastUpdated(com.google.protobuf.Timestamp value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (lastUpdated_ != null &&
          lastUpdated_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        lastUpdated_ =
          com.google.protobuf.Timestamp.newBuilder(lastUpdated_).mergeFrom(value).buildPartial();
      } else {
        lastUpdated_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 9;</code>
     */
    private void clearLastUpdated() {  lastUpdated_ = null;
      
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!name_.isEmpty()) {
        output.writeString(1, getName());
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      if (!email_.isEmpty()) {
        output.writeString(3, getEmail());
      }
      for (int i = 0; i < phones_.size(); i++) {
        output.writeMessage(4, phones_.get(i));
      }
      if (lastUpdated_ != null) {
        output.writeMessage(9, getLastUpdated());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (!email_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getEmail());
      }
      for (int i = 0; i < phones_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, phones_.get(i));
      }
      if (lastUpdated_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getLastUpdated());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.tutorial.AddressBookProtos.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.tutorial.AddressBookProtos.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.tutorial.AddressBookProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.tutorial.AddressBookProtos.Person prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * [START messages]
     * </pre>
     *
     * Protobuf type {@code tutorial.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.tutorial.AddressBookProtos.Person, Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Person)
        com.example.tutorial.AddressBookProtos.PersonOrBuilder {
      // Construct using com.example.tutorial.AddressBookProtos.Person.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string name = 1;</code>
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <pre>
       * Unique ID number for this person.
       * </pre>
       *
       * <code>int32 id = 2;</code>
       */
      @java.lang.Override
      public int getId() {
        return instance.getId();
      }
      /**
       * <pre>
       * Unique ID number for this person.
       * </pre>
       *
       * <code>int32 id = 2;</code>
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <pre>
       * Unique ID number for this person.
       * </pre>
       *
       * <code>int32 id = 2;</code>
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>string email = 3;</code>
       */
      @java.lang.Override
      public java.lang.String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>string email = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      /**
       * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
       */
      @java.lang.Override
      public java.util.List<com.example.tutorial.AddressBookProtos.Person.PhoneNumber> getPhonesList() {
        return java.util.Collections.unmodifiableList(
            instance.getPhonesList());
      }
      /**
       * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
       */
      @java.lang.Override
      public int getPhonesCount() {
        return instance.getPhonesCount();
      }/**
       * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
       */
      @java.lang.Override
      public com.example.tutorial.AddressBookProtos.Person.PhoneNumber getPhones(int index) {
        return instance.getPhones(index);
      }
      /**
       * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
       */
      public Builder setPhones(
          int index, com.example.tutorial.AddressBookProtos.Person.PhoneNumber value) {
        copyOnWrite();
        instance.setPhones(index, value);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
       */
      public Builder setPhones(
          int index, com.example.tutorial.AddressBookProtos.Person.PhoneNumber.Builder builderForValue) {
        copyOnWrite();
        instance.setPhones(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(com.example.tutorial.AddressBookProtos.Person.PhoneNumber value) {
        copyOnWrite();
        instance.addPhones(value);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(
          int index, com.example.tutorial.AddressBookProtos.Person.PhoneNumber value) {
        copyOnWrite();
        instance.addPhones(index, value);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(
          com.example.tutorial.AddressBookProtos.Person.PhoneNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addPhones(builderForValue);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(
          int index, com.example.tutorial.AddressBookProtos.Person.PhoneNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addPhones(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
       */
      public Builder addAllPhones(
          java.lang.Iterable<? extends com.example.tutorial.AddressBookProtos.Person.PhoneNumber> values) {
        copyOnWrite();
        instance.addAllPhones(values);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
       */
      public Builder clearPhones() {
        copyOnWrite();
        instance.clearPhones();
        return this;
      }
      /**
       * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
       */
      public Builder removePhones(int index) {
        copyOnWrite();
        instance.removePhones(index);
        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp last_updated = 9;</code>
       */
      @java.lang.Override
      public boolean hasLastUpdated() {
        return instance.hasLastUpdated();
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 9;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getLastUpdated() {
        return instance.getLastUpdated();
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 9;</code>
       */
      public Builder setLastUpdated(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setLastUpdated(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 9;</code>
       */
      public Builder setLastUpdated(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setLastUpdated(builderForValue);
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 9;</code>
       */
      public Builder mergeLastUpdated(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeLastUpdated(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 9;</code>
       */
      public Builder clearLastUpdated() {  copyOnWrite();
        instance.clearLastUpdated();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Person)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.tutorial.AddressBookProtos.Person();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          phones_.makeImmutable();
          return null;
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.example.tutorial.AddressBookProtos.Person other = (com.example.tutorial.AddressBookProtos.Person) arg1;
          name_ = visitor.visitString(!name_.isEmpty(), name_,
              !other.name_.isEmpty(), other.name_);
          id_ = visitor.visitInt(id_ != 0, id_,
              other.id_ != 0, other.id_);
          email_ = visitor.visitString(!email_.isEmpty(), email_,
              !other.email_.isEmpty(), other.email_);
          phones_= visitor.visitList(phones_, other.phones_);
          lastUpdated_ = visitor.visitMessage(lastUpdated_, other.lastUpdated_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  java.lang.String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                case 16: {

                  id_ = input.readInt32();
                  break;
                }
                case 26: {
                  java.lang.String s = input.readStringRequireUtf8();

                  email_ = s;
                  break;
                }
                case 34: {
                  if (!phones_.isModifiable()) {
                    phones_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(phones_);
                  }
                  phones_.add(
                      input.readMessage(com.example.tutorial.AddressBookProtos.Person.PhoneNumber.parser(), extensionRegistry));
                  break;
                }
                case 74: {
                  com.google.protobuf.Timestamp.Builder subBuilder = null;
                  if (lastUpdated_ != null) {
                    subBuilder = lastUpdated_.toBuilder();
                  }
                  lastUpdated_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(lastUpdated_);
                    lastUpdated_ = subBuilder.buildPartial();
                  }

                  break;
                }
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.tutorial.AddressBookProtos.Person> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.tutorial.AddressBookProtos.Person.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:tutorial.Person)
    private static final com.example.tutorial.AddressBookProtos.Person DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new Person();
    }

    public static com.example.tutorial.AddressBookProtos.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Person> PARSER;

    public static com.google.protobuf.Parser<Person> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AddressBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.AddressBook)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    java.util.List<com.example.tutorial.AddressBookProtos.Person> 
        getPeopleList();
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    com.example.tutorial.AddressBookProtos.Person getPeople(int index);
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    int getPeopleCount();
  }
  /**
   * <pre>
   * Our address book file is just one of these.
   * </pre>
   *
   * Protobuf type {@code tutorial.AddressBook}
   */
  public  static final class AddressBook extends
      com.google.protobuf.GeneratedMessageLite<
          AddressBook, AddressBook.Builder> implements
      // @@protoc_insertion_point(message_implements:tutorial.AddressBook)
      AddressBookOrBuilder {
    private AddressBook() {
      people_ = emptyProtobufList();
    }
    public static final int PEOPLE_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.example.tutorial.AddressBookProtos.Person> people_;
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.tutorial.AddressBookProtos.Person> getPeopleList() {
      return people_;
    }
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public java.util.List<? extends com.example.tutorial.AddressBookProtos.PersonOrBuilder> 
        getPeopleOrBuilderList() {
      return people_;
    }
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    @java.lang.Override
    public int getPeopleCount() {
      return people_.size();
    }
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    @java.lang.Override
    public com.example.tutorial.AddressBookProtos.Person getPeople(int index) {
      return people_.get(index);
    }
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public com.example.tutorial.AddressBookProtos.PersonOrBuilder getPeopleOrBuilder(
        int index) {
      return people_.get(index);
    }
    private void ensurePeopleIsMutable() {
      if (!people_.isModifiable()) {
        people_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(people_);
       }
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    private void setPeople(
        int index, com.example.tutorial.AddressBookProtos.Person value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePeopleIsMutable();
      people_.set(index, value);
    }
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    private void setPeople(
        int index, com.example.tutorial.AddressBookProtos.Person.Builder builderForValue) {
      ensurePeopleIsMutable();
      people_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    private void addPeople(com.example.tutorial.AddressBookProtos.Person value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePeopleIsMutable();
      people_.add(value);
    }
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    private void addPeople(
        int index, com.example.tutorial.AddressBookProtos.Person value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePeopleIsMutable();
      people_.add(index, value);
    }
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    private void addPeople(
        com.example.tutorial.AddressBookProtos.Person.Builder builderForValue) {
      ensurePeopleIsMutable();
      people_.add(builderForValue.build());
    }
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    private void addPeople(
        int index, com.example.tutorial.AddressBookProtos.Person.Builder builderForValue) {
      ensurePeopleIsMutable();
      people_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    private void addAllPeople(
        java.lang.Iterable<? extends com.example.tutorial.AddressBookProtos.Person> values) {
      ensurePeopleIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, people_);
    }
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    private void clearPeople() {
      people_ = emptyProtobufList();
    }
    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    private void removePeople(int index) {
      ensurePeopleIsMutable();
      people_.remove(index);
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < people_.size(); i++) {
        output.writeMessage(1, people_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < people_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, people_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.example.tutorial.AddressBookProtos.AddressBook parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.tutorial.AddressBookProtos.AddressBook parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.tutorial.AddressBookProtos.AddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.tutorial.AddressBookProtos.AddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.tutorial.AddressBookProtos.AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.tutorial.AddressBookProtos.AddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.tutorial.AddressBookProtos.AddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.tutorial.AddressBookProtos.AddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.tutorial.AddressBookProtos.AddressBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.tutorial.AddressBookProtos.AddressBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.tutorial.AddressBookProtos.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.tutorial.AddressBookProtos.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.tutorial.AddressBookProtos.AddressBook prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Our address book file is just one of these.
     * </pre>
     *
     * Protobuf type {@code tutorial.AddressBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.tutorial.AddressBookProtos.AddressBook, Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.AddressBook)
        com.example.tutorial.AddressBookProtos.AddressBookOrBuilder {
      // Construct using com.example.tutorial.AddressBookProtos.AddressBook.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .tutorial.Person people = 1;</code>
       */
      @java.lang.Override
      public java.util.List<com.example.tutorial.AddressBookProtos.Person> getPeopleList() {
        return java.util.Collections.unmodifiableList(
            instance.getPeopleList());
      }
      /**
       * <code>repeated .tutorial.Person people = 1;</code>
       */
      @java.lang.Override
      public int getPeopleCount() {
        return instance.getPeopleCount();
      }/**
       * <code>repeated .tutorial.Person people = 1;</code>
       */
      @java.lang.Override
      public com.example.tutorial.AddressBookProtos.Person getPeople(int index) {
        return instance.getPeople(index);
      }
      /**
       * <code>repeated .tutorial.Person people = 1;</code>
       */
      public Builder setPeople(
          int index, com.example.tutorial.AddressBookProtos.Person value) {
        copyOnWrite();
        instance.setPeople(index, value);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person people = 1;</code>
       */
      public Builder setPeople(
          int index, com.example.tutorial.AddressBookProtos.Person.Builder builderForValue) {
        copyOnWrite();
        instance.setPeople(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person people = 1;</code>
       */
      public Builder addPeople(com.example.tutorial.AddressBookProtos.Person value) {
        copyOnWrite();
        instance.addPeople(value);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person people = 1;</code>
       */
      public Builder addPeople(
          int index, com.example.tutorial.AddressBookProtos.Person value) {
        copyOnWrite();
        instance.addPeople(index, value);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person people = 1;</code>
       */
      public Builder addPeople(
          com.example.tutorial.AddressBookProtos.Person.Builder builderForValue) {
        copyOnWrite();
        instance.addPeople(builderForValue);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person people = 1;</code>
       */
      public Builder addPeople(
          int index, com.example.tutorial.AddressBookProtos.Person.Builder builderForValue) {
        copyOnWrite();
        instance.addPeople(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person people = 1;</code>
       */
      public Builder addAllPeople(
          java.lang.Iterable<? extends com.example.tutorial.AddressBookProtos.Person> values) {
        copyOnWrite();
        instance.addAllPeople(values);
        return this;
      }
      /**
       * <code>repeated .tutorial.Person people = 1;</code>
       */
      public Builder clearPeople() {
        copyOnWrite();
        instance.clearPeople();
        return this;
      }
      /**
       * <code>repeated .tutorial.Person people = 1;</code>
       */
      public Builder removePeople(int index) {
        copyOnWrite();
        instance.removePeople(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.AddressBook)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.tutorial.AddressBookProtos.AddressBook();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          people_.makeImmutable();
          return null;
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.example.tutorial.AddressBookProtos.AddressBook other = (com.example.tutorial.AddressBookProtos.AddressBook) arg1;
          people_= visitor.visitList(people_, other.people_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  if (!people_.isModifiable()) {
                    people_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(people_);
                  }
                  people_.add(
                      input.readMessage(com.example.tutorial.AddressBookProtos.Person.parser(), extensionRegistry));
                  break;
                }
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.tutorial.AddressBookProtos.AddressBook> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.tutorial.AddressBookProtos.AddressBook.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:tutorial.AddressBook)
    private static final com.example.tutorial.AddressBookProtos.AddressBook DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new AddressBook();
    }

    public static com.example.tutorial.AddressBookProtos.AddressBook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AddressBook> PARSER;

    public static com.google.protobuf.Parser<AddressBook> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
